version: '3'
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - my_network

  chrome:
    container_name: 'chrome'
    image: selenium/node-chrome-debug:3.14.0
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - "5900:5900"
    networks:
      - my_network

  django:
    container_name: 'django'
    build: ./django-uwsgi-nginx
    working_dir: /code/source_capture/
    volumes:
      - ./django-uwsgi-nginx/source_capture:/code/source_capture:Z
    ports:
      - '8080:8080'
    links:
      - selenium-hub:hub
    networks:
      - my_network
networks:
  my_network:
    external: true